import type { Metadata } from "next";
import "@repo/ui/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="w-screen h-screen ">
      <body className="w-full h-full">
        <main className="mx-auto max-w-[1200px] w-full h-full">{children}</main>
      </body>
    </html>
  );
}
